name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: configure
      run: ./configure CFLAGS="-march=native -O2 -Ofast -flto -DUSE_ASM -pg" --with-crypto=/usr/local/opt/openssl --with-curl=/usr/local/opt/curl
      
    - name: Install dependencies
      run: make
      
    - name: Run check
      run: make check
      
    - name: Run distcheck
      run: make distcheck
